import type { IProfileRepository } from "@/lib/repositories/IProfileRepository";
import type { ChildProfileData } from "@/lib/child-profile/childProfileStorage";
import type { SupabaseClient } from "@/lib/supabase/client";
import type { Database } from "@/types/supabase";
import { dbToDomainProfile, domainToDbProfile } from "./mappers";
import { QueryError, warnRepo } from "./errors";
import { localRead, localWrite, localRemove } from "@/lib/storage/local/localStorageClient";
import { STORAGE_KEYS, getScopedStorageKey } from "@/lib/storage/storageKeys";
import { ChildProfileDataSchema, parseOrNull } from "@/lib/validation";

// ── Stable server snapshot ────────────────────────────────────────────────────
const SERVER_PROFILE: ChildProfileData | null = null;
const SUPABASE_EMPTY_PROFILES: ChildProfileData[] = [];

/**
 * Supabase-backed IProfileRepository with full multi-child support.
 *
 * Architecture:
 *  • _profiles  — ordered list of all children for the authenticated user
 *  • _cache     — the currently selected child (getProfile() result)
 *  • _selectedChildId — persisted to localStorage for page-reload survival
 *
 * Write strategy: optimistic (sync) + fire-and-forget Supabase sync.
 *  saveProfile() updates the in-memory list immediately so the UI
 *  responds without waiting for the network. The actual INSERT/UPDATE
 *  runs in the background. When the INSERT resolves, the placeholder
 *  id ("child-xxx") is swapped for the real UUID generated by the DB.
 *  This avoids a race between the UUID swap and the caller's selectChild().
 *
 * Selected child persistence: localStorage (scoped by userId).
 *  The Supabase DB has no user_settings table (Phase 8.1), so the
 *  selected-child ID is kept in localStorage only. On hydration, the
 *  saved ID is matched against the fetched profiles; falls back to the
 *  first profile when no match (e.g., that child was deleted).
 */
export class SupabaseProfileRepository implements IProfileRepository {
  private _profiles: ChildProfileData[] = SUPABASE_EMPTY_PROFILES;
  private _cache: ChildProfileData | null = null;
  private _selectedChildId: string | null = null;

  private readonly _listeners = new Set<() => void>();
  private _hydrated = false;
  private _hydratePromise: Promise<void> | null = null;
  private _hydrateGen = 0;
  private _localScopeUserId: string | null = null;

  constructor(private readonly client: SupabaseClient<Database>) {}

  /** Called by RepositoryProvider on every auth transition. */
  public setScope(userId: string | null): void {
    this._localScopeUserId = userId;
  }

  // ── Key helpers ──────────────────────────────────────────────────────────────

  private _profilesListKey(): string {
    return getScopedStorageKey(STORAGE_KEYS.PROFILES_LIST, this._localScopeUserId);
  }
  private _selectedChildKey(): string {
    return getScopedStorageKey(STORAGE_KEYS.SELECTED_CHILD_ID, this._localScopeUserId);
  }
  private _legacyProfileKey(): string {
    return getScopedStorageKey(STORAGE_KEYS.PROFILE, this._localScopeUserId);
  }

  // ── useSyncExternalStore plumbing ────────────────────────────────────────────

  getProfile(): ChildProfileData | null {
    return this._cache;
  }

  getServerProfile(): ChildProfileData | null {
    return SERVER_PROFILE;
  }

  subscribe(callback: () => void): () => void {
    this._listeners.add(callback);
    this._triggerHydrate();
    return () => {
      this._listeners.delete(callback);
    };
  }

  // ── Write operations ─────────────────────────────────────────────────────────

  /**
   * Add or update a child profile.
   *
   * Resolves immediately after the optimistic in-memory update so the caller
   * can call selectChild() while the placeholder id is still valid.
   * The Supabase INSERT/UPDATE is fired in the background; when INSERT
   * returns the real UUID, _replaceProfile() swaps the placeholder automatically.
   */
  async saveProfile(profile: ChildProfileData): Promise<void> {
    const existsInList = this._profiles.some(p => p.id === profile.id);
    const isNew = profile.id.startsWith("child-") || !existsInList;

    // Optimistic update — resolves before Supabase responds
    this._mergeProfile(profile);
    this._persistToLocalStorage();

    // Background sync; errors are logged but never thrown to caller
    void this._syncToSupabase(profile, isNew);
  }

  async replaceProfile(profile: ChildProfileData): Promise<void> {
    await this.saveProfile(profile);
  }

  async clearProfile(): Promise<void> {
    this._profiles = SUPABASE_EMPTY_PROFILES;
    this._cache = null;
    this._selectedChildId = null;
    this._clearLocalStorage();
    this._notify();

    const userId = await this._getCurrentUserId();
    if (!userId) return;

    const { error } = await this.client
      .from("child_profiles")
      .delete()
      .eq("user_id", userId);

    if (error) {
      warnRepo("SupabaseProfileRepository.clearProfile",
        new QueryError("child_profiles", "delete", error));
    }
  }

  // ── Multi-child support ──────────────────────────────────────────────────────

  listProfiles(): ChildProfileData[] {
    return this._profiles;
  }

  getSelectedChildId(): string | null {
    return this._selectedChildId;
  }

  setSelectedChildId(id: string): void {
    if (this._selectedChildId === id) return;
    this._selectedChildId = id;
    const found = this._profiles.find(p => p.id === id);
    if (found) this._cache = found;
    localWrite(this._selectedChildKey(), id);
    this._notify();
  }

  // ── Session boundary ─────────────────────────────────────────────────────────

  public reset(): void {
    if (process.env.NODE_ENV !== "production") {
      console.debug("[SupabaseProfileRepository] reset — clearing cache");
    }
    this._hydrateGen++;
    this._hydrated = false;
    this._hydratePromise = null;
    this._localScopeUserId = null;
    this._cache = null;
    this._profiles = SUPABASE_EMPTY_PROFILES;
    this._selectedChildId = null;
    this._notify();
  }

  public rehydrate(): void {
    if (process.env.NODE_ENV !== "production") {
      console.debug("[SupabaseProfileRepository] rehydrate triggered");
    }
    this._hydrated = false;
    this._hydratePromise = null;
    this._hydrateGen++;
    this._triggerHydrate();
  }

  // ── Private helpers ──────────────────────────────────────────────────────────

  /**
   * Add a new profile to the list or update an existing one.
   * Auto-selects when adding the FIRST profile or a brand-new one
   * (no prior selection). Callers can override via setSelectedChildId().
   */
  private _mergeProfile(profile: ChildProfileData): void {
    const idx = this._profiles.findIndex(p => p.id === profile.id);
    if (idx >= 0) {
      // Update existing
      const next = [...this._profiles];
      next[idx] = profile;
      this._profiles = next;
      if (this._cache?.id === profile.id) this._cache = profile;
    } else {
      // New profile — append and auto-select (first child or new child creation)
      this._profiles = [...this._profiles, profile];
      this._selectedChildId = profile.id;
      this._cache = profile;
    }
    this._notify();
  }

  /**
   * Swap a placeholder id with the canonical UUID returned by Supabase.
   * Updates _selectedChildId and _cache if they reference the old id.
   */
  private _replaceProfile(oldId: string, canonical: ChildProfileData): void {
    const idx = this._profiles.findIndex(p => p.id === oldId);
    if (idx >= 0) {
      const next = [...this._profiles];
      next[idx] = canonical;
      this._profiles = next;
    } else {
      this._profiles = [...this._profiles, canonical];
    }
    if (this._cache?.id === oldId) this._cache = canonical;
    if (this._selectedChildId === oldId) {
      this._selectedChildId = canonical.id;
      localWrite(this._selectedChildKey(), canonical.id);
    }
    this._notify();
  }

  /** Write all profiles + selected child to localStorage for offline fallback. */
  private _persistToLocalStorage(): void {
    if (this._profiles.length > 0) {
      localWrite(this._profilesListKey(), JSON.stringify(this._profiles));
    }
    if (this._selectedChildId) {
      localWrite(this._selectedChildKey(), this._selectedChildId);
    }
    // Write-through to legacy single-profile key for backward-compat reads
    if (this._cache) {
      localWrite(this._legacyProfileKey(), JSON.stringify(this._cache));
    }
  }

  private _clearLocalStorage(): void {
    localRemove(this._profilesListKey());
    localRemove(this._selectedChildKey());
    localRemove(this._legacyProfileKey());
  }

  /** Load profiles from localStorage. Tries PROFILES_LIST first, then legacy PROFILE key. */
  private _loadFromLocalStorage(): void {
    const listRaw = localRead(this._profilesListKey());
    if (listRaw) {
      try {
        const parsed: unknown = JSON.parse(listRaw);
        if (Array.isArray(parsed) && parsed.length > 0) {
          const profiles = (parsed as unknown[]).filter(
            (item): item is ChildProfileData =>
              parseOrNull(ChildProfileDataSchema, item, "supabase-profiles-fallback") !== null,
          );
          if (profiles.length > 0) {
            this._profiles = profiles;
            const savedId = localRead(this._selectedChildKey());
            const selected = profiles.find(p => p.id === savedId) ?? profiles[0] ?? null;
            this._selectedChildId = selected?.id ?? null;
            this._cache = selected;
            return;
          }
        }
      } catch { /* fall through */ }
    }
    // Fallback: legacy single-profile key
    const legacyRaw = localRead(this._legacyProfileKey());
    if (!legacyRaw) return;
    try {
      const profile = parseOrNull(
        ChildProfileDataSchema,
        JSON.parse(legacyRaw),
        "supabase-profile-legacy",
      ) as ChildProfileData | null;
      if (profile) {
        this._profiles = [profile];
        this._selectedChildId = profile.id;
        this._cache = profile;
      }
    } catch { /* ignore */ }
  }

  private _notify(): void {
    this._listeners.forEach(cb => cb());
  }

  private _triggerHydrate(): void {
    if (this._hydratePromise) return;
    this._hydratePromise = this._hydrate().catch(err => {
      warnRepo("SupabaseProfileRepository._hydrate", err);
    });
  }

  private async _hydrate(): Promise<void> {
    const myGen = this._hydrateGen;

    // Owner-only fetch: the child_profiles "grantee select" RLS policy would
    // otherwise leak shared children into this owned list, breaking the
    // owned-vs-shared split that useChildProfile and ChildSelector depend on.
    const userId = await this._getCurrentUserId();
    if (!userId || this._hydrateGen !== myGen) {
      this._loadFromLocalStorage();
      this._hydrated = true;
      this._notify();
      return;
    }

    const { data: rows, error } = await this.client
      .from("child_profiles")
      .select("*")
      .eq("user_id", userId)
      .order("created_at", { ascending: true });

    if (this._hydrateGen !== myGen) return;

    if (error) {
      warnRepo("SupabaseProfileRepository._hydrate",
        new QueryError("child_profiles", "select", error));
      this._loadFromLocalStorage();
      this._hydrated = true;
      this._notify();
      return;
    }

    if (rows && rows.length > 0) {
      const profiles = rows.map(row => dbToDomainProfile(row));
      this._profiles = profiles;
      // Restore selection: prefer the saved ID; fall back to first profile
      const savedId = localRead(this._selectedChildKey());
      const selected = profiles.find(p => p.id === savedId) ?? profiles[0] ?? null;
      this._selectedChildId = selected?.id ?? null;
      this._cache = selected;
      // Write through so offline fallback is always fresh
      this._persistToLocalStorage();
    } else {
      // No rows in Supabase — try localStorage (unauthenticated or pre-migration)
      this._loadFromLocalStorage();
    }

    this._hydrated = true;
    this._notify();
  }

  /**
   * Background Supabase sync for saveProfile().
   * INSERT for new profiles (placeholder id); UPDATE for existing.
   * On INSERT success, swaps the placeholder id with the real DB UUID.
   */
  private async _syncToSupabase(profile: ChildProfileData, isNew: boolean): Promise<void> {
    const userId = await this._getCurrentUserId();
    if (!userId) {
      warnRepo("SupabaseProfileRepository._syncToSupabase",
        "no auth user — profile saved locally only");
      return;
    }

    if (isNew) {
      const { data, error } = await this.client
        .from("child_profiles")
        .insert(domainToDbProfile(profile, userId, profile.targetSound))
        .select("id, updated_at")
        .single();

      if (error) {
        warnRepo("SupabaseProfileRepository._syncToSupabase.insert",
          new QueryError("child_profiles", "insert", error));
      } else if (data) {
        const row = data as { id: string; updated_at: string };
        const canonical: ChildProfileData = { ...profile, id: row.id, updatedAt: row.updated_at };
        this._replaceProfile(profile.id, canonical);
        this._persistToLocalStorage();
      }
    } else {
      const { error } = await this.client
        .from("child_profiles")
        .update({
          name: profile.name,
          age: profile.age,
          target_sound: profile.targetSound,
          training_goal: profile.trainingGoal,
          updated_at: new Date().toISOString(),
        })
        .eq("id", profile.id)
        .eq("user_id", userId);

      if (error) {
        warnRepo("SupabaseProfileRepository._syncToSupabase.update",
          new QueryError("child_profiles", "update", error));
      }
    }
  }

  private async _getCurrentUserId(): Promise<string | null> {
    const { data } = await this.client.auth.getUser();
    return data.user?.id ?? null;
  }
}
